using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerAudio : MonoBehaviour
{
    public AudioSource jumpAudio;
    public AudioSource dashAudio;
    public AudioSource starAudio;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void PlayJumpAudio()
    {
        jumpAudio.Play();
    }

    public void PlayDashAudio()
    {
        dashAudio.Play();
    }

    public void PlayStarAudio()
    {
        starAudio.Play();
    }

}
